name: CI

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - ruby-head
          - 3.0
          - 2.7
          - 2.6
          - 2.5
          - jruby
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.ruby == 'ruby-head' || matrix.os == 'windows-latest' || matrix.os == 'macos-latest' }}
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Install Geos (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get install libgeos-dev -y
      - name: Install Geos (Mac)
        if: matrix.os == 'macos-latest'
        run: |
          brew install geos
      - name: Install Geos (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          vcpkg install geos
      - name: LS Windows
        if: matrix.os == 'windows-latest'
        run: |
          ls C:/vcpkg
          ls C:/vcpkg/installed/x86-windows/share/
          ls C:/vcpkg/installed/x86-windows/share/geos
          ls C:/vcpkg/installed/x86-windows/include
          ls C:/vcpkg/installed/x86-windows/include/geos
      - name: Run Tests (Not Windows)
        if: matrix.os != 'windows-latest'
        run: |
          bundle exec rake
      - name: Run Tests (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          export C_INCLUDE_PATH=C:/vcpkg/installed/x86-windows/include
          bundle exec rake -- --with-geos_c-dir=C:/vcpkg/installed/x86-windows/include
